trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  LT_USERNAME: 'robovipin'
  LT_ACCESS_KEY: 'bX3VZpiN4Tp7cLD7MTfoXqqOZK3q7Xov7UcSCwGQkzf1MEB6bI'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g protractor
    cd conf
    protractor single.conf.js
  displayName: 'npm install and build'
