trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  LT_USERNAME: 'robovipin'
  LT_ACCESS_KEY: 'bX3VZpiN4Tp7cLD7MTfoXqqOZK3q7Xov7UcSCwGQkzf1MEB6bI'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

jobs:
- job: SetupTunnel_1
  steps:
  - script: wget https://s3.amazonaws.com/lambda-tunnel/LT_Linux.zip
 
- job: SetupTunnel_2
  dependsOn: SetupTunnel_1
  steps:
  - script: sudo apt-get install unzip
  
- job: SetupTunnel_3
  dependsOn: SetupTunnel_2
  steps:
  - script: unzip LT_Linux.zip
  
- job: SetupTunnel_4
  dependsOn: SetupTunnel_3
  steps:
  - script: ./LT -user robovipin -key bX3VZpiN4Tp7cLD7MTfoXqqOZK3q7Xov7UcSCwGQkzf1MEB6bI
  
- job: RunTests
  dependsOn: SetupTunnel_4
  steps:
  - script: |
    npm install
    npm install -g protractor
    cd conf
    protractor local.conf.js
  displayName: 'npm install and run tests'
