trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  LT_USERNAME: 'robovipin'
  LT_ACCESS_KEY: 'bX3VZpiN4Tp7cLD7MTfoXqqOZK3q7Xov7UcSCwGQkzf1MEB6bI'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

jobs:
- job: SetupTunnel
  steps:
  - script: |
    wget https://s3.amazonaws.com/lambda-tunnel/LT_Linux.zip
    sudo apt-get install unzip
    unzip LT_Linux.zip
    ./LT -user robovipin -key bX3VZpiN4Tp7cLD7MTfoXqqOZK3q7Xov7UcSCwGQkzf1MEB6bI

- job: RunTests
  dependsOn: SetupTunnel
  steps:
  - script: |
    npm install
    npm install -g protractor
    cd conf
    protractor local.conf.js
  displayName: 'npm install and run tests'
